language: ruby
rvm:
  - "1.9.3"
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "export DISPLAY=:99.0"
before_script:
  - mysql -e "create database IF NOT EXISTS transactional_capybara_test;" -uroot
  - psql -c 'create database transactional_capybara_test;' -U postgres
  - "cp spec/{.travis.,}config.yml"
script: bundle exec rake test:all
cache: bundler
